### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by foxxnuaa** [openimsdk/openim-sdk-core#808] opened 2024-12-07 08:44 UTC
### OpenIM SDK Version

3.8.2

### OpenIM Server Version

3.8.2

### SDK Platform

Web WASM SDK

### Device Model

CentOS7.6

### Operating System Version

CentOS7.6

### Bug Description and Steps to Reproduce

When build wasm sdk in 3.8.2,will report internal/interaction/ws_js.go:30:2: reading nhooyr.io/websocket/go.mod at revision v1.8.10: unknown revision v1.8.10.

**Comment by FGadvancer** [comment] 2024-12-09 11:42
Hello, this issue will be fixed in the next version. It is caused by a change in the repository address of a third-party dependency package. You can also add the following line to your [go.mod](https://github.com/openimsdk/openim-sdk-core/blob/main/go.mod) file:

`replace nhooyr.io/websocket => github.com/coder/websocket v1.8.10`
Then, run `go mod tidy` and try generating the WASM again.

**Closed** 2024-12-09 15:03 UTC
Labels: bug
